openapi: 3.0.4
info:
  title: Company Name Generator
  description: Company Name Generator is a simple tool for generating company names. It returns a list of company names based on the specified keyword.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/companynamegenerator:
    get:
      summary: Generate Company Names
      description: Company Name Generator is a simple tool for generating company names. It returns a list of company names based on the specified keyword.
      operationId: companynamegenerator
      parameters:
      - name: keyword
        in: query
        schema:
          type: string
        required: true
        description: The keyword to generate company names from
        example: systems
      - name: count
        default: '1'
        in: query
        schema:
          type: integer
        required: false
        description: The number of company names to generate (between 1 and 10)
        example: '5'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  keyword: systems
                  count: '5'
                  names:
                  - MakeSystems
                  - SystemsCape
                  - SystemsDash
                  - SystemsIde
                  - SparkSystems
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
